### ISSUE TITLE
Can't install from node-red

### ISSUE THREAD

**Issue by logicalshrapnel** [Stormpass/node-red-contrib-amqp#3]
Installation from node-red palette fail with:
2023-10-30T20:13:46.236Z [err]  500 Internal Server Error - GET https://registry.npmjs.org/@stormpass%2fnode-red-contrib-amqp - KV GET failed: 401 Unauthorized

That URL is not working. I believe the correct URL should be:
https://registry.npmjs.org/package/node-red-contrib-amqp

A quick glace compared to others give me the guess that you should not have your username as part of the name on package.json

**Comment by Stormpass** [comment]
this repos was fork from
https://registry.npmjs.org/package/node-red-contrib-amqp
i change some code，and i release this package in my namespace @stormpass
so they are two different repos(or package)
